FROM mariadb:11.4

# MariaDB defaults to exposing 3306, but we'll explicitly note it here.
# Note: This port will not be mapped to the host machine as per docker-compose configs (for security).
EXPOSE 3306
